export const ORDERS_FETCH_ACTION = 'jpAdmin/Orders/ORDERS_FETCH_ACTION';
export const ORDERS_FETCH_SUCCESS_ACTION = 'jpAdmin/Orders/ORDERS_FETCH_SUCCESS_ACTION';
export const ORDERS_FETCH_FAIL_ACTION = 'jpAdmin/Orders/ORDERS_FETCH_FAIL_ACTION';
