export const EXPENSES_FETCH_ACTION = 'jpAdmin/Expenses/EXPENSES_FETCH_ACTION';
export const EXPENSES_FETCH_SUCCESS_ACTION = 'jpAdmin/Expenses/EXPENSES_FETCH_SUCCESS_ACTION';
export const EXPENSES_FETCH_FAIL_ACTION = 'jpAdmin/Expenses/EXPENSES_FETCH_FAIL_ACTION';
