export const CUSTOMERS_FETCH_ACTION = 'jpAdmin/Customers/CUSTOMERS_FETCH_ACTION';
export const CUSTOMERS_FETCH_SUCCESS_ACTION = 'jpAdmin/Customers/CUSTOMERS_FETCH_SUCCESS_ACTION';
export const CUSTOMERS_FETCH_FAIL_ACTION = 'jpAdmin/Customers/CUSTOMERS_FETCH_FAIL_ACTION';

export const CUSTOMERDETAIL_FETCH_ACTION = 'jpAdmin/Customers/CUSTOMERDETAIL_FETCH_ACTION';
export const CUSTOMERDETAIL_FETCH_SUCCESS_ACTION = 'jpAdmin/Customers/CUSTOMERDETAIL_FETCH_SUCCESS_ACTION';
export const CUSTOMERDETAIL_FETCH_FAIL_ACTION = 'jpAdmin/Customers/CUSTOMERDETAIL_FETCH_FAIL_ACTION';

export const EMPLOYEES_SUGGESTION_FETCH_ACTION = 'jpAdmin/Customers/EMPLOYEES_SUGGESTION_FETCH_ACTION';
export const EMPLOYEES_SUGGESTION_FETCH_SUCCESS_ACTION = 'jpAdmin/Customers/EMPLOYEES_SUGGESTION_FETCH_SUCCESS_ACTION';
export const EMPLOYEES_SUGGESTION_FETCH_FAIL_ACTION = 'jpAdmin/Customers/EMPLOYEES_SUGGESTION_FETCH_FAIL_ACTION';
