export const CUSTOMERS_FETCH_ACTION = 'jpAdmin/Dashboard/CUSTOMERS_FETCH_ACTION';
export const CUSTOMERS_FETCH_SUCCESS_ACTION = 'jpAdmin/Dashboard/CUSTOMERS_FETCH_SUCCESS_ACTION';
export const CUSTOMERS_FETCH_FAIL_ACTION = 'jpAdmin/Dashboard/CUSTOMERS_FETCH_FAIL_ACTION';

export const EXPENSES_FETCH_ACTION = 'jpAdmin/Dashboard/EXPENSES_FETCH_ACTION';
export const EXPENSES_FETCH_SUCCESS_ACTION = 'jpAdmin/Dashboard/EXPENSES_FETCH_SUCCESS_ACTION';
export const EXPENSES_FETCH_FAIL_ACTION = 'jpAdmin/Dashboard/EXPENSES_FETCH_FAIL_ACTION';
